- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy website files from GCS
      command: gsutil cp gs://gcp-terraform-ansible-deployment-bucket/index.html /var/www/html/index.html

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
